# Generated by Django 5.2.3 on 2025-06-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracklike',
            name='is_like',
            field=models.BooleanField(default=True),
        ),
    ]
