# Generated by Django 5.2.3 on 2025-06-27 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_trackcomment_updated_at_trackcomment_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackcomment',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.track'),
        ),
    ]
