# Generated by Django 5.2.3 on 2025-06-27 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_trackcomment_track'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_type', models.CharField(choices=[('private', 'Личный чат'), ('group', 'Групповой чат')], default='private', max_length=10, verbose_name='Тип чата')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название чата')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='chat_avatars/', verbose_name='Аватар чата')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_chats', to=settings.AUTH_USER_MODEL, verbose_name='Администратор')),
                ('participants', models.ManyToManyField(related_name='chats', to=settings.AUTH_USER_MODEL, verbose_name='Участники')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('text', 'Текст'), ('image', 'Изображение'), ('audio', 'Аудио'), ('file', 'Файл'), ('system', 'Системное')], default='text', max_length=10, verbose_name='Тип сообщения')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Содержимое')),
                ('image', models.ImageField(blank=True, null=True, upload_to='message_images/', verbose_name='Изображение')),
                ('audio', models.FileField(blank=True, null=True, upload_to='message_audio/', verbose_name='Аудио')),
                ('file', models.FileField(blank=True, null=True, upload_to='message_files/', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('is_edited', models.BooleanField(default=False, verbose_name='Отредактировано')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='main.chat', verbose_name='Чат')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='main.message', verbose_name='Ответ на сообщение')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Участник'), ('admin', 'Администратор'), ('owner', 'Владелец')], default='member', max_length=10, verbose_name='Роль')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата присоединения')),
                ('is_muted', models.BooleanField(default=False, verbose_name='Заглушен')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='main.chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_memberships', to=settings.AUTH_USER_MODEL)),
                ('last_read_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='read_by', to='main.message', verbose_name='Последнее прочитанное сообщение')),
            ],
            options={
                'verbose_name': 'Участие в чате',
                'verbose_name_plural': 'Участия в чатах',
                'unique_together': {('chat', 'user')},
            },
        ),
    ]
