# Generated by Django 5.2 on 2026-03-21 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_searchquery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='release_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата релиза'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('track_upload', 'Загрузил трек'), ('track_like', 'Лайкнул трек'), ('user_follow', 'Подписался на пользователя'), ('playlist_create', 'Создал плейлист'), ('comment_add', 'Добавил комментарий'), ('album_upload', 'Загрузил альбом'), ('album_release', 'Запланировал релиз')], max_length=20, verbose_name='Тип активности'),
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='albums/covers/', verbose_name='Обложка')),
                ('visibility', models.CharField(choices=[('public', 'Публичный'), ('unlisted', 'По ссылке'), ('private', 'Приватный')], default='public', max_length=10, verbose_name='Видимость')),
                ('release_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата релиза')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to=settings.AUTH_USER_MODEL, verbose_name='Артист')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='main.album', verbose_name='Альбом'),
        ),
        migrations.AddField(
            model_name='track',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='main.album', verbose_name='Альбом'),
        ),
        migrations.CreateModel(
            name='TrackPlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays', to='main.track')),
            ],
            options={
                'verbose_name': 'Прослушивание',
                'verbose_name_plural': 'Прослушивания',
            },
        ),
    ]
