# Generated by Django 5.2 on 2026-03-21 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_track_release_at_alter_activity_activity_type_album_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок в альбоме'),
        ),
    ]
