# Generated by Django 6.0.4 on 2026-05-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_track_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата принятия лицензионного соглашения'),
        ),
    ]
