"""
Django settings for zobeclub project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from django.urls import reverse_lazy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-uc)sp@nup=!#qca276pznt1vxe1#l7g1h9x74l6l(s89%li9ji'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition
INSTALLED_APPS = [
    "unfold", 
    "unfold.contrib.filters", 
    "unfold.contrib.forms",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'main.middleware.LastSeenMiddleware',
]

ROOT_URLCONF = 'zobeclub.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'zobeclub.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# Папки со статическими файлами во время разработки
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Папка для сбора всех статических файлов в продакшене
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Медиафайлы (загруженные пользователями файлы)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Настройки авторизации
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/profile/'
LOGOUT_REDIRECT_URL = '/'

# Настройки для безопасного удаления файлов
FILE_UPLOAD_PERMISSIONS = 0o644
FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o755

# Максимальный размер загружаемых файлов (15MB)
FILE_UPLOAD_MAX_MEMORY_SIZE = 15728640  # 15MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 15728640  # 15MB

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Настройки Unfold — тёмная тема с зелёным акцентом
UNFOLD = {
    "SITE_TITLE": "ZobeClub",
    "SITE_HEADER": "ZobeClub Admin",
    "SITE_URL": "/",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "THEME": "dark",

    "COLORS": {
        # Базовый фон — как на основном сайте (#121212 / #1e1e1e)
        "base": {
            "50":  "245 246 247",
            "100": "227 232 238",
            "200": "200 204 208",
            "300": "154 160 168",
            "400": "107 107 107",
            "500": "74 74 74",
            "600": "46 46 46",     # #2e2e2e — бордеры
            "700": "39 39 39",     # #272727
            "800": "30 30 30",     # #1e1e1e — карточки/сайдбар
            "900": "18 18 18",     # #121212 — основной фон
            "950": "7 7 7",
        },
        # Акцент — кислотный зелёный (#59d344)
        "primary": {
            "50":  "236 253 231",
            "100": "209 249 201",
            "200": "166 242 156",
            "300": "119 232 103",
            "400": "89 211 68",
            "500": "67 185 48",
            "600": "45 159 30",
            "700": "32 121 20",
            "800": "22 89 14",
            "900": "14 62 9",
            "950": "7 35 4",
        },
        "font": {
            "subtle-light": "115 115 115",
            "subtle-dark":  "154 160 168",   # #9aa0a8 — видимый серый
            "default-light": "38 38 38",
            "default-dark":  "227 232 238",  # #e3e8ee — основной текст
            "important-light": "10 10 10",
            "important-dark":  "245 245 245",
        },
    },

    # Кастомный CSS — исправляем выпадающие списки и select
    "STYLES": [
        "/static/css/admin_fix.css",
    ],
}